const { contextBridge, ipcRenderer } = require('electron');

const api = {
  getGames: () => ipcRenderer.invoke('get-games'),
  launchGame: (id) => ipcRenderer.invoke('launch-game', id),
  captureGameplay: (id) => ipcRenderer.invoke('capture-gameplay', id),
  rescan: () => ipcRenderer.invoke('rescan'),
  addGame: (data) => ipcRenderer.invoke('add-game', data),
  removeGame: (id) => ipcRenderer.invoke('remove-game', id),
  deleteGameFromDisk: (id) => ipcRenderer.invoke('delete-game-from-disk', id),
  searchArtwork: (name) => ipcRenderer.invoke('search-artwork', name),
  getArtworkConfig: () => ipcRenderer.invoke('get-artwork-config'),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  openUpdateUrl: (url) => ipcRenderer.invoke('open-update-url', url),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_, d) => cb(d)),
  setCover: (id, dataUrlOrUrl) => ipcRenderer.invoke('set-cover', id, dataUrlOrUrl),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: (s) => ipcRenderer.invoke('set-settings', s),
  getCustomFolders: () => ipcRenderer.invoke('get-custom-folders'),
  addCustomFolder: (p) => ipcRenderer.invoke('add-custom-folder', p),
  removeCustomFolder: (p) => ipcRenderer.invoke('remove-custom-folder', p),
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  selectExecutable: () => ipcRenderer.invoke('select-executable'),
  getEmulators: () => ipcRenderer.invoke('get-emulators'),
  addEmulator: (emulator) => ipcRenderer.invoke('add-emulator', emulator),
  removeEmulator: (id) => ipcRenderer.invoke('remove-emulator', id),
  openFolder: (p) => ipcRenderer.invoke('open-folder', p),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  checkEnv: () => ipcRenderer.invoke('check-env'),
  exportConfig: () => ipcRenderer.invoke('export-config'),
  importConfig: () => ipcRenderer.invoke('import-config'),
  getGameInfo: (game) => ipcRenderer.invoke('get-game-info', game),
  getPlatforms: () => ipcRenderer.invoke('get-platforms'),
  toggleFullscreen: () => ipcRenderer.send('window-fullscreen'),
  getWindowFullscreen: () => ipcRenderer.invoke('get-window-fullscreen'),
  setArcadeFullscreen: (on) => ipcRenderer.invoke('set-arcade-fullscreen', on),
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),

  onGameAdded: (cb) => ipcRenderer.on('game-added', (_, g) => cb(g)),
  onGameRemoved: (cb) => ipcRenderer.on('game-removed', (_, id) => cb(id)),
  onScanProgress: (cb) => ipcRenderer.on('scan-progress', (_, d) => cb(d)),
  onScanComplete: (cb) => ipcRenderer.on('scan-complete', (_, d) => cb(d)),
  onEmulatorsUpdated: (cb) => ipcRenderer.on('emulators-updated', (_, d) => cb(d))
};

contextBridge.exposeInMainWorld('gamevault', api);